### ISSUE TITLE
Scene Inventory - "Filter outdated" and "Update All" not working

### ISSUE THREAD

**Issue by LiborBatek** [ynput/ayon-blender#39] opened 2024-09-17 15:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When triggering Scene Inventory and perform these actions it does nothing...aka broken atm.

### Expected Behavior:

Should work as normally, when hitting "Filter outdated" filterning valid entries and when triggering "Update All Outdated to Latest" should load the newest  versions.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Load some asset versions (mixture of outdated ones and not outdated)
2. Perform ```AYON > Manage``` and use ```Filter Outdated``` and ```Update All```
3. It wont perform those correctly resulting into no action.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by BigRoy** [comment] 2024-09-17 21:58
I think this is a duplicate of https://github.com/ynput/ayon-blender/issues/40 but with less information. Closing.

**Closed by BigRoy** 2024-09-17 21:58 UTC
Labels: type: bug
