### ISSUE TITLE
Publisher not using Task level attributes but Folder level attributes only

### ISSUE THREAD

**Issue by LiborBatek** [ynput/ayon-blender#50] opened 2024-09-18 09:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When performing some override on a task level (like frame range) it still uses when doing validations the folder level attributes.

For e.g. Review and when checking if correct frame range set.

### Expected Behavior:

Publisher should use task level attribs for validation as other host apps.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Create task level override in AYON (e.g. shot frame range) which differs to folder level attrib
2. Set your frame range following the override values (which should differ to folder level attribs)
3. Create camera obejct and ```Review``` publish instance using that camera
4. Publisher will still validate against folder level attribs not the task level override

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by BigRoy** [comment] 2024-09-18 09:57
I think this is a duplicate of https://github.com/ynput/ayon-blender/issues/41

Can you confirm @LiborBatek - if so, close it.

**Comment by LiborBatek** [comment] 2024-09-18 19:41
Redundant Issue which can be closed...

**Closed** 2024-09-18 19:40 UTC
Labels: type: bug
